### ISSUE TITLE
There is any way to update SVGO plugin?

### ISSUE THREAD

**Issue by Xaviju** [juanfran/svgo-inkscape#1]
I am a user, I download and install this extension from this repo. 
If there is an update on SVGO how could I update my extension?

**Comment by juanfran** [comment]
I'll try to launch a new svgo-inkscape version for every svgo. But you can go to `extensions/svgo-inkscape` and update svgo `npm install svgo --save`. If the svgo api hasn't changed should work.

**Comment by Xaviju** [comment]
I would send a PR to update this part in the README :smile:
