### ISSUE TITLE
Can not save with svgo-inkscape v1.0.0 (Windows 10 - Inkscape 1.0 and 1.1)

### ISSUE THREAD

**Issue by hansnolte** [juanfran/svgo-inkscape#11]
With svgo-inkscape v0.1.1 warnings are issued, but the result is mostly correct.
![v011](https://user-images.githubusercontent.com/7922627/92619261-91fb5900-f2c1-11ea-810e-693e15e22853.jpg)

With svgo-inkscape v1.0.0 I cannot save at all.
![1](https://user-images.githubusercontent.com/7922627/92619106-637d7e00-f2c1-11ea-9870-01b508153276.jpg)

**Comment by vmario89** [comment]
i did some small fixes for svgo-inkscape some time ago at our collection space > https://gitea.fablabchemnitz.de/MarioVoigt/mightyscape-1.X/src/branch/master/extensions/fablabchemnitz/svgo-inkscape

**Comment by hansnolte** [comment]
Hi Mario,
that's great!
It took me half a dozen attempts to download the archive, but at some point it worked.
svgo-inkscape works perfectly with Inkscape 1.0 and 1.0.1.

Thank you very very much
Hans

**Comment by juanfran** [comment]
@hansnolte thanks por reporting! it should be fixed here https://github.com/juanfran/svgo-inkscape/releases/tag/v1.0.1
