### ISSUE TITLE
Windows installation instructions need correction

### ISSUE THREAD

**Issue by KolyaKorruptis** [juanfran/svgo-inkscape#13]
The instructions for installation on Windows are incorrect in a few points:

1. You should not extract the archive as stated in the instructions, since it contains a root folder **svgo-inkscape-windows64**. The contents of this folder need to be extracted (that is the sub-folder named **svgo-inkscape** and a file named **svgo-inkscape.inx**).
2. The target folder is not C:\Program Files\Inkscape\share\extensions as stated but `C:\Program Files\Inkscape\share\inkscape\extensions\`

I'm using the current release v1.0.1 and Inkscape at v1.1.1

**Comment by juanfran** [comment]
Thanks! I updated the README.md
