### ISSUE TITLE
Support for Windows platform

### ISSUE THREAD

**Issue by duarteframos** [juanfran/svgo-inkscape#3]
As requested by Xaviju Julián on a [Google plus post] (https://plus.google.com/u/0/108683735417375178984/posts/LbkZ79gmN6m) I posted an issue to support Windows platform to help keep track on user's interest.

**Comment by juanfran** [comment]
I will try to do it in a few hours, thanks :smile:

**Comment by juanfran** [comment]
Done, check the README

**Comment by duarteframos** [comment]
Well that was quick.
From my very quick test seems to be working fine, at least 32 bits version, will try 64 at home.
Thanks :)

**Comment by duarteframos** [comment]
64bits version also seems to be working fine under Windows 7, from my very quick test.
Thanks again
